[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@chainlink/=node_modules/@chainlink/",
  "forge-std/=lib/forge-std/src/"
]

fs_permissions = [{ access = "read", path = ".env" }]